### PR TITLE
Automatic prompt generation for colabdesign

### PR DESCRIPTION
**Pull request by phiflei**
## What type of PR is this? 

- 🎮 Feature

## Description

_Generate prompts automatically from a pdb inputs file. More specifically, we generate a list of contigs_override prompts based on random masking of contact domains._

## Steps to Test

_Added the script prompt_generator.py which contains the function generate_full_prompts that returns the list of prompts and various helper functions, including one to determine contact residues, compute domains from contact residues, and a function to perform random masking._

## Relevant GIF 

_Required 🐔_

### CODE REVIEW

**Comment by phiflei** [comment]
Not ready for review yet!

**Comment by phiflei** [comment]
The code is ready for review now! There is a running version on stg. I made one test run and it goes through as it should. Here is some more info about it:

The good model version on stg is
sokrypton/colabdesign gateway automatic - VV

Parameters:
- protein complex pdb needs to have two chain, one for the target and one for the binder. Examples are UROK_HUMAN_1-133.pdb, BioCD202b18_aa_7fd4f_unrelaxed_rank_001_alphafold2_multimer_v3_model_5_seed_000.pdb, or pretty much any of the other pdbs in data.
- select target chain (often A) and binder chain (often B)
- you can choose start and end target residue, but if you leave it blank then start and end of the target chain will be chosen automatically.
- cutoff is the distance defining contact residues between target and binder chain.
- domain threshold you can play a tiny bit with but a value close to 6 is probably reasonable.
- you can just play with the masking probabilities, e.g. trying 0 or 1 as extreme values
- n prompts is the number of prompts generated.

That's it I think. It's more or less self-explanatory.

Happy model breaking! :wink:

**Review by thetechnocrat-dev — CHANGES_REQUESTED** [review]
Just some high level changes to implement as we test the model

1) There are some extra files I think you pulled from staging at some point that are not in main
* tools/nonfileparamtest/*
* tools/paramtest/*

2) as ahmed pointed out, the license file was deleted and needs added back

**Review by acashmoney — APPROVED** [review]
Was able to get this working on stg ✅ 

Screenshot 2023-12-01 at 1 45 57 PM

**Review by thetechnocrat-dev — APPROVED** [review]
Just kicked off some stuff on a local box for some probing, but the tool looks good to merge, so Corey can poke around on prod as well.

Screenshot 2023-12-13 at 11 45 37 AM

**Pull request merged**
